import { fieldElements } from "../messages.js";

// Rules of the built-in validator, keyed by the data-val-* rule name. They cover the attributes generated by
// ASP.NET Core's DataAnnotations adapters and FluentValidation's client adapters.
// A rule gets (value, element, params, form) and returns true, false, a message, or a Promise of one of them.
// Rules other than "required" and "equalto" are skipped when the value is empty (like jQuery Validation).

export const rules = Object.create(null);

export function addRule(name, validate) {
  rules[String(name).toLowerCase()] = validate;
}

function toNumber(value) {
  // Both "." and "," are accepted as the decimal separator (issue with comma cultures in jQuery Validation).
  return value === "" || value == null ? NaN : Number(String(value).trim().replace(",", "."));
}

// Like jQuery Validation: a select and a group of checkboxes count the chosen items, the way [MinLength] and
// [MaxLength] count the items of a collection on the server. Other fields count characters.
function lengthOf(value, element, form) {
  if (element.tagName === "SELECT") {
    return Array.from(element.options).filter((o) => o.selected).length;
  }

  if (element.type === "checkbox" || element.type === "radio") {
    return fieldElements(form, element.name).filter((e) => e.checked).length;
  }

  return value.length;
}

addRule("required", (value) => value.trim() !== "");

addRule("length", (value, element, params, form) => {
  const length = lengthOf(value, element, form);
  return (!params.min || length >= Number(params.min)) && (!params.max || length <= Number(params.max));
});

addRule("minlength", (value, element, params, form) => lengthOf(value, element, form) >= Number(params.min));

addRule("maxlength", (value, element, params, form) => lengthOf(value, element, form) <= Number(params.max));

addRule("range", (value, element, params) => {
  const number = toNumber(value);
  if (isNaN(number)) {
    return false;
  }
  const min = toNumber(params.min);
  const max = toNumber(params.max);
  return (isNaN(min) || number >= min) && (isNaN(max) || number <= max);
});

addRule("number", (value) => /^[-+]?(\d+([.,]\d*)?|[.,]\d+)$/.test(value.trim()));

// The whole value must match, like [RegularExpression] on the server. A .NET pattern JavaScript can't parse is left
// to the server instead of blocking the form.
addRule("regex", (value, element, params) => {
  let expression;

  try {
    expression = new RegExp(params.pattern);
  } catch (e) {
    console.warn("FormHelper: the pattern of " + element.name + " is not valid in JavaScript; it is validated on the server only.", e);
    return true;
  }

  const match = expression.exec(value);
  return !!match && match.index === 0 && match[0].length === value.length;
});

// Same expression as jQuery Validation (the HTML5 email definition).
addRule("email", (value) =>
  /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(value));

addRule("url", (value) => {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:" || url.protocol === "ftp:";
  } catch (e) {
    return false;
  }
});

// Close to .NET's PhoneAttribute: digits, spaces, + - . ( ) and an optional extension.
addRule("phone", (value) => {
  const number = value.trim().replace(/\s*(x|ext\.?|extension)\s*\d+$/i, "");
  return /^\+?[\d\s().-]+$/.test(number) && /\d/.test(number);
});

addRule("creditcard", (value) => {
  if (/[^0-9 \-]+/.test(value)) {
    return false;
  }

  const digits = value.replace(/\D/g, "");
  if (digits.length < 13 || digits.length > 19) {
    return false;
  }

  let sum = 0;
  let even = false;

  for (let n = digits.length - 1; n >= 0; n--) {
    let digit = parseInt(digits.charAt(n), 10);
    if (even && (digit *= 2) > 9) {
      digit -= 9;
    }
    sum += digit;
    even = !even;
  }

  return sum % 10 === 0;
});

// data-val-equalto-other="*.Password": "*." is replaced with the prefix of the current field (like Unobtrusive).
addRule("equalto", (value, element, params, form) => {
  let other = params.other || "";

  if (other.indexOf("*.") === 0) {
    const name = element.name;
    const prefix = name.substr(0, name.lastIndexOf(".") + 1);
    other = prefix + other.substr(2);
  }

  const target = fieldElements(form, other)[0];
  return !target || target.value === value;
});

// [Remote]: asks the server. data-val-remote-url, -type (GET/POST) and -additionalfields ("*.Email,*.Id").
// The action returns true, false or an error message (like jQuery Validation Unobtrusive).
const remoteRequests = new WeakMap();

addRule("remote", (value, element, params, form) => {
  if (!params.url) {
    return true;
  }

  const method = (params.type || "GET").toUpperCase();
  const prefix = element.name.substr(0, element.name.lastIndexOf(".") + 1);
  const data = new URLSearchParams();

  String(params.additionalfields || element.name)
    .split(",")
    .map((field) => field.trim())
    .filter(Boolean)
    .map((field) => (field.indexOf("*.") === 0 ? prefix + field.substr(2) : field))
    .forEach((field) => data.append(field, remoteFieldValue(form, field)));

  // The same values are not sent again (e.g. focusout after the submit already checked them).
  const key = method + " " + params.url + "?" + data.toString();
  const previous = remoteRequests.get(element);

  if (previous && previous.key === key) {
    return previous.promise;
  }

  const headers = { "X-Requested-With": "XMLHttpRequest", "Accept": "application/json" };
  let request;

  if (method === "GET") {
    request = fetch(params.url + (params.url.indexOf("?") === -1 ? "?" : "&") + data.toString(), { headers, credentials: "same-origin" });
  } else {
    const token = form.querySelector("input[name=\"__RequestVerificationToken\"]");
    if (token) {
      headers["RequestVerificationToken"] = token.value;
    }
    headers["Content-Type"] = "application/x-www-form-urlencoded; charset=UTF-8";
    request = fetch(params.url, { method, headers, body: data, credentials: "same-origin" });
  }

  const promise = request
    .then((response) => {
      if (!response.ok) {
        throw new Error("HTTP " + response.status);
      }
      return response.json();
    })
    .then((result) => {
      if (result === true || result === "true") {
        return true;
      }
      return typeof result === "string" && result !== "" ? result : false;
    })
    .catch((error) => {
      // An unreachable check doesn't block the form; the server validates the post anyway.
      console.warn("FormHelper: remote validation failed (" + params.url + ").", error);
      remoteRequests.delete(element);
      return true;
    });

  remoteRequests.set(element, { key, promise });
  return promise;
});

// Like Unobtrusive: a checkbox sends its value when checked, otherwise ASP.NET's hidden "false".
function remoteFieldValue(form, name) {
  const elements = fieldElements(form, name);
  const first = elements[0];

  if (!first) {
    return "";
  }

  if (first.type === "checkbox" || first.type === "radio") {
    const checked = elements.find((e) => (e.type === "checkbox" || e.type === "radio") && e.checked);
    const hidden = elements.find((e) => e.type === "hidden");
    return checked ? checked.value : hidden ? hidden.value : "";
  }

  return first.value;
}

addRule("fileextensions", (value, element, params) => {
  const allowed = String(params.extensions || "png,jpg,jpeg,gif")
    .split(",")
    .map((e) => e.trim().replace(/^\./, "").toLowerCase())
    .filter(Boolean);

  const names = element.files && element.files.length > 0
    ? Array.from(element.files).map((f) => f.name)
    : [value];

  return names.every((name) => allowed.indexOf(name.split(".").pop().toLowerCase()) !== -1);
});
